name: unihair
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - fastapi==0.115.12
      - filelock==3.18.0
      - flask==2.3.2
      - flask-cors==4.0.0
      - h11==0.14.0
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.24.3
      - pillow==10.0.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - python-multipart==0.0.20
      - requests==2.31.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.13.3
      - torch==2.0.1
      - torchvision==0.15.2
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - uvicorn==0.34.1
      - werkzeug==3.1.3
